# Generated by Django 2.1.5 on 2019-04-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_Images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Server.User'),
        ),
    ]
