# Generated by Django 2.1.5 on 2019-04-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0003_achievement_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achivement',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
