# Generated by Django 2.1.5 on 2019-04-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0005_auto_20190427_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='Player',
            new_name='player',
        ),
    ]
