# Generated by Django 2.1.5 on 2019-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0006_auto_20190427_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gameID',
            field=models.IntegerField(default=0),
        ),
    ]
