# Generated by Django 2.1.5 on 2019-04-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0007_match_gameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Server.Match')),
            ],
        ),
    ]
