# Generated by Django 2.1.5 on 2019-04-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0008_game_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='gameID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Server.Match'),
        ),
    ]
