# Generated by Django 2.1.5 on 2019-04-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0013_auto_20190428_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gameID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='gameID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Data_Server.Match'),
        ),
    ]
