# Generated by Django 2.1.5 on 2019-04-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0014_auto_20190428_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='gameID',
        ),
    ]
