# Generated by Django 2.1.5 on 2019-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0016_auto_20190428_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='word',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
