# Generated by Django 2.1.5 on 2019-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0018_remove_game_data_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='gameID',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
