# Generated by Django 2.1.5 on 2019-04-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0020_auto_20190428_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_data',
            name='gameID',
        ),
    ]
