# Generated by Django 2.1.5 on 2019-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Server', '0022_auto_20190429_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='p1_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game_data',
            name='p2_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
